//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementSystem.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskManagementSystem.Client.Resources.LocalizedResources", typeof(LocalizedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error.
        /// </summary>
        internal static string BaseProxy_InternalServerError {
            get {
                return ResourceManager.GetString("BaseProxy_InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have access to this url {0}.
        /// </summary>
        internal static string BaseProxy_SendRequestAsync_YouDontHaveAccessToThisUrl {
            get {
                return ResourceManager.GetString("BaseProxy_SendRequestAsync_YouDontHaveAccessToThisUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled status code: {0}.
        /// </summary>
        internal static string BaseProxy_UnhandledStatusCode {
            get {
                return ResourceManager.GetString("BaseProxy_UnhandledStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next month.
        /// </summary>
        internal static string CalendarComponent_NextMonth {
            get {
                return ResourceManager.GetString("CalendarComponent_NextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous month.
        /// </summary>
        internal static string CalendarComponent_PreviousMonth {
            get {
                return ResourceManager.GetString("CalendarComponent_PreviousMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string ChangePasswordComponent_NewPassword {
            get {
                return ResourceManager.GetString("ChangePasswordComponent_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password (repeat).
        /// </summary>
        internal static string ChangePasswordComponent_NewPasswordRepeat {
            get {
                return ResourceManager.GetString("ChangePasswordComponent_NewPasswordRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        internal static string ChangePasswordComponent_OldPassword {
            get {
                return ResourceManager.GetString("ChangePasswordComponent_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password change.
        /// </summary>
        internal static string ChangePasswordComponent_PasswordChange {
            get {
                return ResourceManager.GetString("ChangePasswordComponent_PasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password successfully changed.
        /// </summary>
        internal static string ChangePasswordComponent_PasswordSuccessfullyChanged {
            get {
                return ResourceManager.GetString("ChangePasswordComponent_PasswordSuccessfullyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit password change.
        /// </summary>
        internal static string ChangePasswordComponent_SubmitPasswordChange {
            get {
                return ResourceManager.GetString("ChangePasswordComponent_SubmitPasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время начала.
        /// </summary>
        internal static string EventEditFormModal_EventEditing {
            get {
                return ResourceManager.GetString("EventEditFormModal_EventEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End time.
        /// </summary>
        internal static string EventEditFormModal_EventEndTime {
            get {
                return ResourceManager.GetString("EventEditFormModal_EventEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string EventEditFormModal_EventName {
            get {
                return ResourceManager.GetString("EventEditFormModal_EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start time.
        /// </summary>
        internal static string EventEditFormModal_EventStartTime {
            get {
                return ResourceManager.GetString("EventEditFormModal_EventStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First day of week.
        /// </summary>
        internal static string LocalizationSettingsComponent_FirstDayOfWeek {
            get {
                return ResourceManager.GetString("LocalizationSettingsComponent_FirstDayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LocalizationSettingsComponent_Language {
            get {
                return ResourceManager.GetString("LocalizationSettingsComponent_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization settings.
        /// </summary>
        internal static string LocalizationSettingsComponent_LocalizationSettings {
            get {
                return ResourceManager.GetString("LocalizationSettingsComponent_LocalizationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save settings.
        /// </summary>
        internal static string LocalizationSettingsComponent_SaveSettings {
            get {
                return ResourceManager.GetString("LocalizationSettingsComponent_SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings change.
        /// </summary>
        internal static string LocalizationSettingsComponent_SettingsChange {
            get {
                return ResourceManager.GetString("LocalizationSettingsComponent_SettingsChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings successfully changed.
        /// </summary>
        internal static string LocalizationSettingsComponent_SettingsSuccessfullyChanged {
            get {
                return ResourceManager.GetString("LocalizationSettingsComponent_SettingsSuccessfullyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © Task Management System {0}.
        /// </summary>
        internal static string LoginComponent_Copyright {
            get {
                return ResourceManager.GetString("LoginComponent_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string LoginComponent_Email {
            get {
                return ResourceManager.GetString("LoginComponent_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string LoginComponent_Login {
            get {
                return ResourceManager.GetString("LoginComponent_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string LoginComponent_Password {
            get {
                return ResourceManager.GetString("LoginComponent_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        internal static string LoginComponent_SignIn {
            get {
                return ResourceManager.GetString("LoginComponent_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Profile_Logout {
            get {
                return ResourceManager.GetString("Profile_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My profile.
        /// </summary>
        internal static string Profile_MyProfile {
            get {
                return ResourceManager.GetString("Profile_MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings_Settings {
            get {
                return ResourceManager.GetString("Settings_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred.
        /// </summary>
        internal static string ToastService_AnErrorHasOccurred {
            get {
                return ResourceManager.GetString("ToastService_AnErrorHasOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        internal static string ToastService_System {
            get {
                return ResourceManager.GetString("ToastService_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About me.
        /// </summary>
        internal static string UserInfoComponent_AboutMe {
            get {
                return ResourceManager.GetString("UserInfoComponent_AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About successfully changed.
        /// </summary>
        internal static string UserInfoComponent_AboutSuccessfullyChanged {
            get {
                return ResourceManager.GetString("UserInfoComponent_AboutSuccessfullyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string UserInfoComponent_Email {
            get {
                return ResourceManager.GetString("UserInfoComponent_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string UserInfoComponent_Name {
            get {
                return ResourceManager.GetString("UserInfoComponent_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register date.
        /// </summary>
        internal static string UserInfoComponent_RegisterDate {
            get {
                return ResourceManager.GetString("UserInfoComponent_RegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit update info.
        /// </summary>
        internal static string UserInfoComponent_SubmitUpdateInfo {
            get {
                return ResourceManager.GetString("UserInfoComponent_SubmitUpdateInfo", resourceCulture);
            }
        }
    }
}
