//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManagementSystem.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizedResources_ru {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizedResources_ru() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TaskManagementSystem.Client.Resources.LocalizedResources.ru", typeof(LocalizedResources_ru).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внутренняя ошибка сервера.
        /// </summary>
        internal static string BaseProxy_InternalServerError {
            get {
                return ResourceManager.GetString("BaseProxy_InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to У вас нет доступа к этой ссылке {0}.
        /// </summary>
        internal static string BaseProxy_SendRequestAsync_YouDontHaveAccessToThisUrl {
            get {
                return ResourceManager.GetString("BaseProxy_SendRequestAsync_YouDontHaveAccessToThisUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необработанный статус запроса {0}.
        /// </summary>
        internal static string BaseProxy_UnhandledStatusCode {
            get {
                return ResourceManager.GetString("BaseProxy_UnhandledStatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Следующий месяц.
        /// </summary>
        internal static string CalendarComponent_NextMonth {
            get {
                return ResourceManager.GetString("CalendarComponent_NextMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предыдущий месяц.
        /// </summary>
        internal static string CalendarComponent_PreviousMonth {
            get {
                return ResourceManager.GetString("CalendarComponent_PreviousMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль.
        /// </summary>
        internal static string ChangePasswordComponent_NewPassword {
            get {
                return ResourceManager.GetString("ChangePasswordComponent_NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новый пароль (повтор).
        /// </summary>
        internal static string ChangePasswordComponent_NewPasswordRepeat {
            get {
                return ResourceManager.GetString("ChangePasswordComponent_NewPasswordRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Старый пароль.
        /// </summary>
        internal static string ChangePasswordComponent_OldPassword {
            get {
                return ResourceManager.GetString("ChangePasswordComponent_OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение пароля.
        /// </summary>
        internal static string ChangePasswordComponent_PasswordChange {
            get {
                return ResourceManager.GetString("ChangePasswordComponent_PasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль успешно изменен.
        /// </summary>
        internal static string ChangePasswordComponent_PasswordSuccessfullyChanged {
            get {
                return ResourceManager.GetString("ChangePasswordComponent_PasswordSuccessfullyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить пароль.
        /// </summary>
        internal static string ChangePasswordComponent_SubmitPasswordChange {
            get {
                return ResourceManager.GetString("ChangePasswordComponent_SubmitPasswordChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время начала.
        /// </summary>
        internal static string EventEditFormModal_EventEditing {
            get {
                return ResourceManager.GetString("EventEditFormModal_EventEditing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время окончания.
        /// </summary>
        internal static string EventEditFormModal_EventEndTime {
            get {
                return ResourceManager.GetString("EventEditFormModal_EventEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        internal static string EventEditFormModal_EventName {
            get {
                return ResourceManager.GetString("EventEditFormModal_EventName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Время начала.
        /// </summary>
        internal static string EventEditFormModal_EventStartTime {
            get {
                return ResourceManager.GetString("EventEditFormModal_EventStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Загрузка....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Первый день недели.
        /// </summary>
        internal static string LocalizationSettingsComponent_FirstDayOfWeek {
            get {
                return ResourceManager.GetString("LocalizationSettingsComponent_FirstDayOfWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        internal static string LocalizationSettingsComponent_Language {
            get {
                return ResourceManager.GetString("LocalizationSettingsComponent_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки локализации.
        /// </summary>
        internal static string LocalizationSettingsComponent_LocalizationSettings {
            get {
                return ResourceManager.GetString("LocalizationSettingsComponent_LocalizationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить настройки.
        /// </summary>
        internal static string LocalizationSettingsComponent_SaveSettings {
            get {
                return ResourceManager.GetString("LocalizationSettingsComponent_SaveSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменение настроек.
        /// </summary>
        internal static string LocalizationSettingsComponent_SettingsChange {
            get {
                return ResourceManager.GetString("LocalizationSettingsComponent_SettingsChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки успешно сохранены.
        /// </summary>
        internal static string LocalizationSettingsComponent_SettingsSuccessfullyChanged {
            get {
                return ResourceManager.GetString("LocalizationSettingsComponent_SettingsSuccessfullyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to © Корпоративный органайзер {0}.
        /// </summary>
        internal static string LoginComponent_Copyright {
            get {
                return ResourceManager.GetString("LoginComponent_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string LoginComponent_Email {
            get {
                return ResourceManager.GetString("LoginComponent_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизоваться.
        /// </summary>
        internal static string LoginComponent_Login {
            get {
                return ResourceManager.GetString("LoginComponent_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пароль.
        /// </summary>
        internal static string LoginComponent_Password {
            get {
                return ResourceManager.GetString("LoginComponent_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Авторизация.
        /// </summary>
        internal static string LoginComponent_SignIn {
            get {
                return ResourceManager.GetString("LoginComponent_SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти из аккаунта.
        /// </summary>
        internal static string Profile_Logout {
            get {
                return ResourceManager.GetString("Profile_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мой аккаунт.
        /// </summary>
        internal static string Profile_MyProfile {
            get {
                return ResourceManager.GetString("Profile_MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки.
        /// </summary>
        internal static string Settings_Settings {
            get {
                return ResourceManager.GetString("Settings_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка.
        /// </summary>
        internal static string ToastService_AnErrorHasOccurred {
            get {
                return ResourceManager.GetString("ToastService_AnErrorHasOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Система.
        /// </summary>
        internal static string ToastService_System {
            get {
                return ResourceManager.GetString("ToastService_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обо мне.
        /// </summary>
        internal static string UserInfoComponent_AboutMe {
            get {
                return ResourceManager.GetString("UserInfoComponent_AboutMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обо мне успешно изменено.
        /// </summary>
        internal static string UserInfoComponent_AboutSuccessfullyChanged {
            get {
                return ResourceManager.GetString("UserInfoComponent_AboutSuccessfullyChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string UserInfoComponent_Email {
            get {
                return ResourceManager.GetString("UserInfoComponent_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        internal static string UserInfoComponent_Name {
            get {
                return ResourceManager.GetString("UserInfoComponent_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата регистрации.
        /// </summary>
        internal static string UserInfoComponent_RegisterDate {
            get {
                return ResourceManager.GetString("UserInfoComponent_RegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить информацию.
        /// </summary>
        internal static string UserInfoComponent_SubmitUpdateInfo {
            get {
                return ResourceManager.GetString("UserInfoComponent_SubmitUpdateInfo", resourceCulture);
            }
        }
    }
}
