name: Deploy to Heroku

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  APP_NAME: ${{ 'tms-etu-8375' }}

jobs:
  build:
    name: Deploy to Heroku
    runs-on: ubuntu-latest
    steps:

    # Clone the repository
    - name: Checkout
      uses: actions/checkout@v3

    # Login to  Heroku Container registry
    - name: Docker login
      run: heroku container:login 
    
    # Build Docker image and push to Heroku Container Registry
    - name: Build&Push
      run: heroku container:push web -a $APP_NAME
      
    # Release new Docker image
    - name: Publish
      run: heroku container:release web -a $APP_NAME
